### ISSUE TITLE
NameError in "tagger_proto_mlp.py" when running "main.py" [NameError: name 'dim_red_bool' is not defined]

### ISSUE THREAD

**Issue by FaizaMalik1** [peterbhase/InterpretableNLP-ACL2020#5]
Hello Mr. Hase, 

I am working with your code from the "InterpretableNLP-ACL2020" repository and encountered a `NameError` when running the `main.py` script with the `ProtoMLP` model configuration. The exact command I used is as follows:

"python main.py --model ProtoMLP --save-name proto-20-push80 --push-after 80"

While the `MLP` model ran successfully without any error, when using the `ProtoMLP` model, I received the following traceback:

"Traceback (most recent call last):
  File "main.py", line 117, in <module>
    tagger = TaggerFactory.create(args, data_encoder, tag_seq_indexer)
  File "/content/InterpretableNLP-ACL2020/tabular/src/factories/factory_tagger.py", line 59, in create
    similarity_function_name = args.similarity_function_name
  File "/content/InterpretableNLP-ACL2020/tabular/src/models/tagger_proto_mlp.py", line 70, in __init__
    self._initialize_weights()
  File "/content/InterpretableNLP-ACL2020/tabular/src/models/tagger_proto_mlp.py", line 231, in _initialize_weights
    if dim_red_bool:
NameError: name 'dim_red_bool' is not defined"

I am working on Google Colab, I followed the setup instructions provided in the repository, ensuring all dependencies were correctly installed.

I have tried to troubleshoot this further but have not been able to resolve the issue. As such, I am reaching out to you for assistance. Could you please help me understand what might be causing this error and how to resolve it?

Thank you very much for your time and any assistance you can provide. 

Best regards,
Faiza Malik

**Comment by peterbhase** [comment]
Hi Faiza,

Thanks for raising the issue. It looks like this could have been from a forgotten assignenment `self.dim_red_bool = dim_red_bool` during initialization of the class. I just updated the file to do so. Could you try now?

**Comment by FaizaMalik1** [comment]
Hello Mr. Hase,

Thank you for your quick response to my previous question.The initial error has been resolved. Unfortunately, I've encountered a new issue, a RuntimeError regarding tensor sizes:

"RuntimeError: The size of tensor a (50) must match the size of tensor b (16) at non-singleton dimension 1"

I made a change to the "_initialize_frozen_dim_red" function which appears to have fixed the issue. However, I'm observing a significant decrease in token-level accuracy. Could you please review the changes I've made and confirm if they are appropriate? Here is the updated function for your reference:

python
def _initialize_weights(self):
    # ... other initialization methods ...

    def _initialize_lin_layer(self):               
        # ... other initialization methods ...

    def _initalize_frozen_dim_red(m):
        if isinstance(m, nn.Linear):
            identity_like = torch.zeros_like(m.weight)  # Create a zero matrix with the same shape as m.weight
            identity_like.fill_diagonal_(1)  # Fill its diagonal with 1's
            m.weight.data.copy_(identity_like)


Any insight you could provide would be greatly appreciated, especially regarding the low token-level accuracy.

Best regards,
Faiza Malik

**Comment by peterbhase** [comment]
I'm not sure what the deal is with the frozen dim reduction, because it just looks like an identity transform. I'd have two recs:
1. Try not use dim reduction
2. Based on lns 232-233, make sure the code is using a random projection and not the `_initalize_frozen_dim_red`

**Comment by FaizaMalik1** [comment]
Hello Mr. Hase,

I hope you're doing well. I've made the adjustments you recommended to the model configuration. Unfortunately, even after implementing those changes, I'm observing a token-level accuracy of 69.60%, which still falls short of the expected 81.90%.

Could you advise me on any further steps I might take to resolve this discrepancy?

Thank you for your continued support.

Best,
Faiza Malik

**Comment by peterbhase** [comment]
Hi Faiza, I'm not sure what the issue would be at this point. I would try replicating the results for the MLP model that doesn't use prototype features first to ensure that the overall training process is working correctly. If the standard MLP works but not the prototype MLP, you could try replicating results with text rather than tabular data. However, the tabular data is pretty simple and the prototype MLP should be competitive with the standard MLP there.
